# Generated by Django 3.2.1 on 2025-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRecords',
            fields=[
                ('agency', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('record', models.TextField()),
                ('status', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyRecords',
            fields=[
                ('owner', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('api_key', models.CharField(max_length=2000, unique=True)),
                ('record', models.TextField()),
                ('status', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntitySeedRecords',
            fields=[
                ('entity', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('entity_seed_records', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectorRecords',
            fields=[
                ('inspector', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('record', models.TextField()),
                ('status', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldSeedReportRecords',
            fields=[
                ('seed_id', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('seed_report', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedReportRecords',
            fields=[
                ('seed_id', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=2000)),
                ('seed_report', models.TextField()),
                ('status', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedTrackRecords',
            fields=[
                ('seed_id', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('record', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('username', models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True)),
                ('records', models.TextField()),
                ('status', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
